# Generated by Django 5.2.7 on 2025-11-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=50)),
                ('Created_Date', models.DateField()),
            ],
        ),
    ]
