# Generated by Django 5.2.7 on 2025-11-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
