# Generated by Django 5.2.7 on 2025-11-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0002_alter_taskmodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Created_Date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Task_Title',
            new_name='task_title',
        ),
    ]
